
import type { Brand, Model, Service, Country, Carrier } from './types';
import { ArgentinaFlag, BoliviaFlag, BrazilFlag, CanadaFlag, ChileFlag, ChinaFlag, ColombiaFlag, FranceFlag, GermanyFlag, IndiaFlag, ItalyFlag, JapanFlag, MexicoFlag, PeruFlag, SouthKoreaFlag, SpainFlag, UnitedKingdomFlag, UnitedStatesFlag } from '@/components/icons/flags';
import { AttLogo, BellLogo, ClaroLogo, DeutscheTelekomLogo, EeLogo, EntelLogo, KtLogo, MovistarLogo, NttDocomoLogo, O2Logo, OrangeLogo, PersonalLogo, RogersLogo, SfrLogo, SoftbankLogo, TelcelLogo, TigoLogo, TimLogo, TMobileLogo, VerizonLogo, VivoLogo, VodafoneLogo, WomLogo } from '@/components/icons/carriers';

export let brands: Brand[] = [
  { id: '1', name: 'Apple' },
  { id: '2', name: 'Samsung' },
  { id: '3', name: 'Xiaomi' },
  { id: '4', name: 'Motorola' },
  { id: '5', name: 'Huawei' },
  { id: '6', name: 'Google' },
  { id: '7', name: 'OnePlus' },
  { id: '8', name: 'Oppo' },
  { id: '9', name: 'Realme' },
  { id: '10', name: 'ZTE' },
  { id: '11', name: 'Sony' },
  { id: '12', name: 'LG' },
  { id: '13', name: 'TCL' },
  { id: '14', name: 'Alcatel' },
  { id: '15', name: 'BLU' },
  { id: '16', name: 'HTC' },
  { id: '17', name: 'Tecno' },
  { id: '18', name: 'Infinix' },
  { id: '19', name: 'Itel' },
  { id: '20', name: 'Sonim' },
];

export let models: Model[] = [
  // Apple (2018+)
  { id: '1', name: 'iPhone 15 Pro Max', brand: 'Apple', category: 'Phone' },
  { id: '2', name: 'iPhone 15 Pro', brand: 'Apple', category: 'Phone' },
  { id: '3', name: 'iPhone 15', brand: 'Apple', category: 'Phone' },
  { id: '4', name: 'iPhone 14 Pro', brand: 'Apple', category: 'Phone' },
  { id: '5', name: 'iPhone 13', brand: 'Apple', category: 'Phone' },
  { id: '6', name: 'iPhone 12', brand: 'Apple', category: 'Phone' },
  { id: '7', name: 'iPhone 11', brand: 'Apple', category: 'Phone' },
  { id: '8', name: 'iPhone SE (2022)', brand: 'Apple', category: 'Phone' },
  { id: '9', name: 'iPhone XR', brand: 'Apple', category: 'Phone' },
  { id: '10', name: 'iPhone XS', brand: 'Apple', category: 'Phone' },
  { id: '11', name: 'MacBook Pro 16 M3', brand: 'Apple', category: 'Mac' },
  { id: '12', name: 'iPad Air (M2)', brand: 'Apple', category: 'iPad' },
  { id: '13', name: 'Apple Watch Ultra 2', brand: 'Apple', category: 'Watch' },

  // Samsung (Deduplicated List)
  { id: 'samsung-a01', name: 'Galaxy A01', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-a01c', name: 'Galaxy A01 Core', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-a02', name: 'Galaxy A02', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-a02s', name: 'Galaxy A02s', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-a03', name: 'Galaxy A03', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-a03c', name: 'Galaxy A03 Core', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-a03s', name: 'Galaxy A03s', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-a04', name: 'Galaxy A04', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-a04e', name: 'Galaxy A04e', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-a04s', name: 'Galaxy A04s', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-a05', name: 'Galaxy A05', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-a05s', name: 'Galaxy A05s', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-a06', name: 'Galaxy A06', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-a10', name: 'Galaxy A10', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-a10e', name: 'Galaxy A10e', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-a10s', name: 'Galaxy A10s', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-a11', name: 'Galaxy A11', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-a12', name: 'Galaxy A12', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-a13', name: 'Galaxy A13', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-a14', name: 'Galaxy A14', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-a15', name: 'Galaxy A15', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-a16', name: 'Galaxy A16', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-a20', name: 'Galaxy A20', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-a20e', name: 'Galaxy A20e', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-a20s', name: 'Galaxy A20s', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-a21', name: 'Galaxy A21', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-a21s', name: 'Galaxy A21s', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-a22', name: 'Galaxy A22', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-a23', name: 'Galaxy A23', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-a24', name: 'Galaxy A24', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-a25', name: 'Galaxy A25', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-a3', name: 'Galaxy A3', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-a30s', name: 'Galaxy A30s', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-a31', name: 'Galaxy A31', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-a32', name: 'Galaxy A32', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-a33', name: 'Galaxy A33 5G', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-a34', name: 'Galaxy A34', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-a35', name: 'Galaxy A35', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-a40', name: 'Galaxy A40', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-a42', name: 'Galaxy A42 5G', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-a5', name: 'Galaxy A5', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-a50', name: 'Galaxy A50', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-a50s', name: 'Galaxy A50s', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-a51', name: 'Galaxy A51', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-a52', name: 'Galaxy A52', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-a52s', name: 'Galaxy A52s 5G', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-a53', name: 'Galaxy A53 5G', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-a54', name: 'Galaxy A54', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-a55', name: 'Galaxy A55', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-a70', name: 'Galaxy A70', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-a71', name: 'Galaxy A71', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-a72', name: 'Galaxy A72', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-a73', name: 'Galaxy A73 5G', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-a80', name: 'Galaxy A80', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-alpha', name: 'Galaxy Alpha', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-s3', name: 'Galaxy S3', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-s4', name: 'Galaxy S4', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-s4m', name: 'Galaxy S4 mini', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-s5', name: 'Galaxy S5', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-s6', name: 'Galaxy S6', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-s6e', name: 'Galaxy S6 EDGE', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-s8', name: 'Galaxy S8', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-s8-active', name: 'Galaxy S8 Active', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-s8-plus', name: 'Galaxy S8 Plus', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-s9', name: 'Galaxy S9', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-s9-plus', name: 'Galaxy S9 Plus', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-s10', name: 'Galaxy S10', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-s10-lite', name: 'Galaxy S10 Lite', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-s10-plus', name: 'Galaxy S10 Plus', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-s10e', name: 'Galaxy S10e', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-s20', name: 'Galaxy S20', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-s20-fe', name: 'Galaxy S20 FE', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-s20-plus', name: 'Galaxy S20 Plus', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-s20-ultra', name: 'Galaxy S20 Ultra', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-s21', name: 'Galaxy S21', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-s21-fe', name: 'Galaxy S21 FE', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-s21-plus', name: 'Galaxy S21 Plus', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-s21-ultra', name: 'Galaxy S21 Ultra', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-s22', name: 'Galaxy S22', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-s22-plus', name: 'Galaxy S22 Plus', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-s22-ultra', name: 'Galaxy S22 Ultra', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-s23', name: 'Galaxy S23', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-s23-fe', name: 'Galaxy S23 FE', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-s23-plus', name: 'Galaxy S23 Plus', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-s23-ultra', name: 'Galaxy S23 Ultra', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-s24', name: 'Galaxy S24', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-s24-fe', name: 'Galaxy S24 FE', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-s24-plus', name: 'Galaxy S24 Plus', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-s24-ultra', name: 'Galaxy S24 Ultra', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-s25', name: 'Galaxy S25', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-s25-plus', name: 'Galaxy S25 Plus', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-s25-ultra', name: 'Galaxy S25 Ultra', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-note3', name: 'Galaxy Note 3', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-note4', name: 'Galaxy Note 4', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-note5', name: 'Galaxy Note 5', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-note8', name: 'Galaxy Note 8', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-note9', name: 'Galaxy Note 9', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-note10', name: 'Galaxy Note 10', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-note10-lite', name: 'Galaxy Note 10 Lite', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-note10-plus', name: 'Galaxy Note 10 Plus', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-note20', name: 'Galaxy Note 20', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-note20-ultra', name: 'Galaxy Note 20 Ultra', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-note-edge', name: 'Galaxy Note Edge', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-fold', name: 'Galaxy Fold', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-z-fold2', name: 'Galaxy Z Fold2', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-z-fold3', name: 'Galaxy Z Fold3', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-z-fold4', name: 'Galaxy Z Fold4', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-z-fold5', name: 'Galaxy Z Fold5', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-z-fold6', name: 'Galaxy Z Fold6', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-z-flip', name: 'Galaxy Z Flip', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-z-flip3', name: 'Galaxy Z Flip3', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-z-flip4', name: 'Galaxy Z Flip4', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-z-flip5', name: 'Galaxy Z Flip5', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-z-flip6', name: 'Galaxy Z Flip6', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-c55', name: 'Galaxy C55', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-f05', name: 'Galaxy F05', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-f14', name: 'Galaxy F14', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-f15', name: 'Galaxy F15', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-f34', name: 'Galaxy F34', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-f55', name: 'Galaxy F55', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-m05', name: 'Galaxy M05', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-m13', name: 'Galaxy M13', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-m14', name: 'Galaxy M14', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-m15', name: 'Galaxy M15', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-m30s', name: 'Galaxy M30s', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-m31', name: 'Galaxy M31', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-m33', name: 'Galaxy M33', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-m35', name: 'Galaxy M35', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-m51', name: 'Galaxy M51', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-m55', name: 'Galaxy M55', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-m55s', name: 'Galaxy M55s', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-j1', name: 'Galaxy J1', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-j1-ace', name: 'Galaxy J1 Ace', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-j2', name: 'Galaxy J2', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-j2-core', name: 'Galaxy J2 Core', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-j2-pure', name: 'Galaxy J2 Pure', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-j3', name: 'Galaxy J3', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-j3-achieve', name: 'Galaxy J3 Achieve', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-j3-emerge', name: 'Galaxy J3 Emerge', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-j3-luna-pro', name: 'Galaxy J3 Luna Pro', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-j3-orbit', name: 'Galaxy J3 Orbit', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-j3-prime', name: 'Galaxy J3 Prime', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-j3-star', name: 'Galaxy J3 Star', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-j4', name: 'Galaxy J4', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-j4-plus', name: 'Galaxy J4 Plus', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-j4-core', name: 'Galaxy J4 Core', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-j5', name: 'Galaxy J5', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-j5-prime', name: 'Galaxy J5 Prime', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-j6', name: 'Galaxy J6', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-j6-plus', name: 'Galaxy J6 Plus', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-j7', name: 'Galaxy J7', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-j7-2016', name: 'Galaxy J7 2016', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-j7-crown', name: 'Galaxy J7 Crown', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-j7-nxt', name: 'Galaxy J7 Nxt', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-j7-perx', name: 'Galaxy J7 Perx', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-j7-prime', name: 'Galaxy J7 Prime', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-j7-pro', name: 'Galaxy J7 Pro', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-j7-refine', name: 'Galaxy J7 Refine', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-j7-sky-pro', name: 'Galaxy J7 Sky Pro', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-j7-star', name: 'Galaxy J7 Star', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-j7-v', name: 'Galaxy J7 V', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-j8', name: 'Galaxy J8', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-y', name: 'Galaxy Y', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-y-pro', name: 'Galaxy Y Pro', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-ace', name: 'Galaxy Ace', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-ace3', name: 'Galaxy Ace 3', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-ace4', name: 'Galaxy Ace 4', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-amp2', name: 'Galaxy Amp 2', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-ampprime', name: 'Galaxy Amp Prime', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-ampprime3', name: 'Galaxy Amp Prime 3', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-coreprime', name: 'Galaxy Core Prime', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-express2', name: 'Galaxy Express 2', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-express3', name: 'Galaxy Express 3', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-expressprime3', name: 'Galaxy Express Prime 3', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-grand2', name: 'Galaxy Grand 2', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-grandneo', name: 'Galaxy Grand Neo', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-grandprime', name: 'Galaxy Grand Prime', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-mini', name: 'Galaxy Mini', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-sol2', name: 'Galaxy Sol 2', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-sol3', name: 'Galaxy Sol 3', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-trend', name: 'Galaxy Trend', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-young', name: 'Galaxy Young', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-xcover-pro', name: 'Galaxy Xcover Pro', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-xcover7', name: 'Galaxy Xcover7', brand: 'Samsung', category: 'Phone' },
  { id: 'samsung-tab-a', name: 'Galaxy Tab A', brand: 'Samsung', category: 'iPad' },
  { id: 'samsung-tab-a-84', name: 'Galaxy Tab A 8.4', brand: 'Samsung', category: 'iPad' },
  { id: 'samsung-tab-a7-lite', name: 'Galaxy Tab A7 Lite', brand: 'Samsung', category: 'iPad' },
  { id: 'samsung-tab-s5e', name: 'Galaxy Tab S5e', brand: 'Samsung', category: 'iPad' },
  { id: 'samsung-tab-s6', name: 'Galaxy Tab S6', brand: 'Samsung', category: 'iPad' },
  { id: 'samsung-tab-s7', name: 'Galaxy Tab S7', brand: 'Samsung', category: 'iPad' },
  { id: 'samsung-tab-s7-fe', name: 'Galaxy Tab S7 FE', brand: 'Samsung', category: 'iPad' },
  { id: 'samsung-tab-s7-plus', name: 'Galaxy Tab S7 Plus', brand: 'Samsung', category: 'iPad' },
  { id: 'samsung-tab-s8-plus', name: 'Galaxy Tab S8 Plus', brand: 'Samsung', category: 'iPad' },
  { id: 'samsung-tab-s10-plus', name: 'Galaxy Tab S10 Plus', brand: 'Samsung', category: 'iPad' },
  { id: 'samsung-tab-s10-ultra', name: 'Galaxy Tab S10 Ultra', brand: 'Samsung', category: 'iPad' },
  { id: 'samsung-tab', name: 'Galaxy Tab', brand: 'Samsung', category: 'iPad' },
  { id: 'samsung-tab3', name: 'Galaxy Tab3', brand: 'Samsung', category: 'iPad' },
  { id: 'samsung-tab4', name: 'Galaxy Tab 4', brand: 'Samsung', category: 'iPad' },
  { id: 'samsung-note-10-1', name: 'Galaxy Note 10.1', brand: 'Samsung', category: 'iPad' },
  { id: 'samsung-gear-s', name: 'Galaxy Gear S', brand: 'Samsung', category: 'Watch' },
  { id: 'samsung-gear-s2', name: 'Galaxy Gear S2', brand: 'Samsung', category: 'Watch' },

  // Xiaomi (2018+)
  { id: '24', name: 'Xiaomi 14 Ultra', brand: 'Xiaomi', category: 'Phone' },
  { id: '25', name: 'Xiaomi 13T Pro', brand: 'Xiaomi', category: 'Phone' },
  { id: '26', name: 'Redmi Note 12', brand: 'Xiaomi', category: 'Phone' },
  { id: '27', name: 'Poco F5 Pro', brand: 'Xiaomi', category: 'Phone' },
  { id: '28', name: 'Redmi Note 11', brand: 'Xiaomi', category: 'Phone' },
  { id: '29', name: 'Poco X5 Pro', brand: 'Xiaomi', category: 'Phone' },

  // Motorola (2018+)
  { id: '30', name: 'Motorola Razr 40 Ultra', brand: 'Motorola', category: 'Phone' },
  { id: '31', name: 'Motorola Edge 40 Pro', brand: 'Motorola', category: 'Phone' },
  { id: '32', name: 'Moto G84', brand: 'Motorola', category: 'Phone' },
  { id: '33', name: 'Moto G54', brand: 'Motorola', category: 'Phone' },
  { id: '34', name: 'Motorola Edge 30', brand: 'Motorola', category: 'Phone' },
  { id: '35', name: 'Moto G Stylus (2022)', brand: 'Motorola', category: 'Phone' },

  // Huawei (2018+)
  { id: '36', name: 'Huawei Pura 70 Ultra', brand: 'Huawei', category: 'Phone' },
  { id: '37', name: 'Huawei P60 Pro', brand: 'Huawei', category: 'Phone' },
  { id: '38', name: 'Huawei Mate 50 Pro', brand: 'Huawei', category: 'Phone' },
  { id: '39', name: 'Huawei Nova 11', brand: 'Huawei', category: 'Phone' },
  { id: '40', name: 'Huawei P40 Pro', brand: 'Huawei', category: 'Phone' },

  // Google (2018+)
  { id: '41', name: 'Pixel 8 Pro', brand: 'Google', category: 'Phone' },
  { id: '42', name: 'Pixel 7a', brand: 'Google', category: 'Phone' },
  { id: '43', name: 'Pixel Fold', brand: 'Google', category: 'Phone' },
  { id: '44', name: 'Pixel 6 Pro', brand: 'Google', category: 'Phone' },
  { id: '45', name: 'Pixel 5', brand: 'Google', category: 'Phone' },
  { id: '46', name: 'Pixel 4a', brand: 'Google', category: 'Phone' },
  { id: '47', name: 'Pixel 3 XL', brand: 'Google', category: 'Phone' },

  // OnePlus (2018+)
  { id: '48', name: 'OnePlus 12', brand: 'OnePlus', category: 'Phone' },
  { id: '49', name: 'OnePlus Open', brand: 'OnePlus', category: 'Phone' },
  { id: '50', name: 'OnePlus Nord 3', brand: 'OnePlus', category: 'Phone' },
  { id: '51', name: 'OnePlus 10 Pro', brand: 'OnePlus', category: 'Phone' },
  { id: '52', name: 'OnePlus 8T', brand: 'OnePlus', category: 'Phone' },
  { id: '53', name: 'OnePlus 7 Pro', brand: 'OnePlus', category: 'Phone' },

  // Oppo
  { id: '54', name: 'Oppo Find X7 Ultra', brand: 'Oppo', category: 'Phone' },
  { id: '55', name: 'Oppo Reno11 Pro', brand: 'Oppo', category: 'Phone' },
  
  // Realme
  { id: '56', name: 'Realme GT5 Pro', brand: 'Realme', category: 'Phone' },
  { id: '57', name: 'Realme 12 Pro+', brand: 'Realme', category: 'Phone' },
  
  // ZTE
  { id: '58', name: 'ZTE Nubia Z60 Ultra', brand: 'ZTE', category: 'Phone' },
  { id: '59', name: 'ZTE Axon 40 Ultra', brand: 'ZTE', category: 'Phone' },
  
  // Sony
  { id: '60', name: 'Sony Xperia 1 V', brand: 'Sony', category: 'Phone' },
  { id: '61', name: 'Sony Xperia 5 IV', brand: 'Sony', category: 'Phone' },
  
  // LG
  { id: '62', name: 'LG Wing', brand: 'LG', category: 'Phone' },
  { id: '63', name: 'LG Velvet', brand: 'LG', category: 'Phone' },

  // TCL
  { id: '64', name: 'TCL 40 NxtPaper', brand: 'TCL', category: 'Phone' },
  
  // Alcatel
  { id: '65', name: 'Alcatel 3X (2020)', brand: 'Alcatel', category: 'Phone' },
  
  // BLU
  { id: '66', name: 'BLU Bold N2', brand: 'BLU', category: 'Phone' },

  // HTC
  { id: '67', name: 'HTC U23 Pro', brand: 'HTC', category: 'Phone' },

  // Tecno
  { id: '68', name: 'Tecno Phantom V Fold', brand: 'Tecno', category: 'Phone' },

  // Infinix
  { id: '69', name: 'Infinix Note 30 Pro', brand: 'Infinix', category: 'Phone' },
  
  // Itel
  { id: '70', name: 'Itel S23+', brand: 'Itel', category: 'Phone' },

  // Sonim
  { id: '71', name: 'Sonim XP10', brand: 'Sonim', category: 'Phone' },
];

export let services: Service[] = [
  { id: '1', name: 'Eliminar Cuenta Google', description: 'Eliminación completa de la cuenta de Google (FRP).', price: 25.00, 
    emoji: '🔒' },
  { id: '2', name: 'Reparacion de IMEI', description: 'Solución a problemas de IMEI (reporte, nul, etc).', price: 50.00, 
    emoji: '📡' },
  { id: '3', name: 'Eliminar Payjoy/MDM', description: 'Remoción de bloqueos de financiamiento o empresariales (MDM).', price: 40.00, 
    emoji: '🛡️' },
  { id: '4', name: 'Liberar SIM', description: 'Desbloqueo de red para usar cualquier operadora.', 
    emoji: '📲' },
  { id: '5', name: 'Eliminar Cuenta Huawei ID', description: 'Eliminación completa de la cuenta de Huawei.', price: 35.00, 
    emoji: '🆔' },
  { id: '6', name: 'Eliminar Cuenta Xiaomi', description: 'Eliminación completa de la cuenta Mi.', price: 35.00, 
    emoji: 'Ⓜ️' },
  { 
    id: '7', 
    name: 'Eliminar Cuenta iCloud', 
    description: 'Eliminación de bloqueo de activación de iCloud. Selecciona el estado de tu dispositivo.',
    emoji: '🍏',
    subServices: [
        { id: '7-1', name: 'iPhone en código/Desactivado', description: 'El dispositivo está en la pantalla de ingreso de código o desactivado', price: 120.00, imageUrl: 'https://images.unsplash.com/photo-1541929866681-94eb7c9a4c7d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwzfHxwYXNzd29yZHxlbnwwfHx8fDE3NTI5ODMyMTd8MA&ixlib=rb-4.1.0&q=80&w=1080', dataAiHint: 'iphone passcode' },
        { id: '7-3', name: 'iPhone pantalla hola', description: 'El dispositivo está en la pantalla de bienvenida "Hola".', price: 150.00, imageUrl: 'https://images.unsplash.com/photo-1681395791877-e7186492ad3a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxOXx8aXBob25lJTIwaGVsbG98ZW58MHx8fHwxNzUyOTgzMzc5fDA&ixlib=rb-4.1.0&q=80&w=1080', dataAiHint: 'iphone hello' },
    ]
  },
  { id: '8', name: 'Eliminar MDM (Administracion Remota)', description: 'Remoción de perfil de administración remota.', price: 60.00, 
    emoji: '⚙️' },
  { 
    id: '9', 
    name: 'Reporte de IMEI', 
    description: 'Servicios relacionados con el estado del IMEI de tu dispositivo.',
    emoji: '📶',
    subServices: [
        { id: '9-1', name: 'Verificar si tiene reporte', description: 'Informe completo para saber si un IMEI está en lista negra.', price: 5.00, 
          iconSvg: `<defs><linearGradient id="check-grad" x1="0%" y1="0%" x2="0%" y2="100%"><stop offset="0%" stopColor="#bbf7d0" /><stop offset="100%" stopColor="#4ade80" /></linearGradient></defs><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8l-6-6z" fill="white" stroke="#d4d4d8" stroke-width="1.5" /><path d="M14 2v6h6" fill="none" stroke="#d4d4d8" stroke-width="1.5" stroke-linejoin="round"/><circle cx="12" cy="15" r="5" fill="url(#check-grad)"/><path d="m10 15l1.5 1.5L14 14" stroke="white" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>` },
        { id: '9-2', name: 'Limpiar reporte', description: 'Servicio de limpieza de IMEI para dispositivos reportados.', price: 80.00, 
          iconSvg: `<defs><linearGradient id="clean-grad" x1="0%" y1="0%" x2="0%" y2="100%"><stop offset="0%" stopColor="#fecaca" /><stop offset="100%" stopColor="#f87171" /></linearGradient></defs><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8l-6-6z" fill="white" stroke="#d4d4d8" stroke-width="1.5" /><path d="M14 2v6h6" fill="none" stroke="#d4d4d8" stroke-width="1.5" stroke-linejoin="round"/><circle cx="12" cy="15" r="5" fill="url(#clean-grad)"/><path d="m10.5 13.5l3 3m0-3l-3 3" stroke="white" stroke-width="2" stroke-linecap="round"/>` },
    ]
  },
];

export const countries: Country[] = [
    { id: 'us', name: 'Estados Unidos', flag: UnitedStatesFlag, phoneCode: '+1' },
    { id: 'mx', name: 'México', flag: MexicoFlag, phoneCode: '+52' },
    { id: 'es', name: 'España', flag: SpainFlag, phoneCode: '+34' },
    { id: 'ar', name: 'Argentina', flag: ArgentinaFlag, phoneCode: '+54' },
    { id: 'bo', name: 'Bolivia', flag: BoliviaFlag, phoneCode: '+591' },
    { id: 'br', name: 'Brasil', flag: BrazilFlag, phoneCode: '+55' },
    { id: 'ca', name: 'Canadá', flag: CanadaFlag, phoneCode: '+1' },
    { id: 'cl', name: 'Chile', flag: ChileFlag, phoneCode: '+56' },
    { id: 'co', name: 'Colombia', flag: ColombiaFlag, phoneCode: '+57' },
    { id: 'pe', name: 'Perú', flag: PeruFlag, phoneCode: '+51' },
    // Europe
    { id: 'de', name: 'Alemania', flag: GermanyFlag, phoneCode: '+49' },
    { id: 'fr', name: 'Francia', flag: FranceFlag, phoneCode: '+33' },
    { id: 'gb', name: 'Reino Unido', flag: UnitedKingdomFlag, phoneCode: '+44' },
    { id: 'it', name: 'Italia', flag: ItalyFlag, phoneCode: '+39' },
    // Asia
    { id: 'cn', name: 'China', flag: ChinaFlag, phoneCode: '+86' },
    { id: 'in', name: 'India', flag: IndiaFlag, phoneCode: '+91' },
    { id: 'jp', name: 'Japón', flag: JapanFlag, phoneCode: '+81' },
    { id: 'kr', name: 'Corea del Sur', flag: SouthKoreaFlag, phoneCode: '+82' },
];

export const carriers: Carrier[] = [
    // Argentina
    { id: 'ar-claro', name: 'Claro', countryId: 'ar', logo: ClaroLogo },
    { id: 'ar-movistar', name: 'Movistar', countryId: 'ar', logo: MovistarLogo },
    { id: 'ar-personal', name: 'Personal', countryId: 'ar', logo: PersonalLogo },
    // Bolivia
    { id: 'bo-entel', name: 'Entel', countryId: 'bo', logo: EntelLogo },
    { id: 'bo-tigo', name: 'Tigo', countryId: 'bo', logo: TigoLogo },
    // Brasil
    { id: 'br-vivo', name: 'Vivo', countryId: 'br', logo: VivoLogo },
    { id: 'br-claro', name: 'Claro', countryId: 'br', logo: ClaroLogo },
    { id: 'br-tim', name: 'TIM', countryId: 'br', logo: TimLogo },
    // Canadá
    { id: 'ca-rogers', name: 'Rogers', countryId: 'ca', logo: RogersLogo },
    { id: 'ca-bell', name: 'Bell', countryId: 'ca', logo: BellLogo },
    { id: 'ca-telus', name: 'Telus', countryId: 'ca' },
    // Chile
    { id: 'cl-entel', name: 'Entel', countryId: 'cl', logo: EntelLogo },
    { id: 'cl-movistar', name: 'Movistar', countryId: 'cl', logo: MovistarLogo },
    { id: 'cl-wom', name: 'WOM', countryId: 'cl', logo: WomLogo },
    // Colombia
    { id: 'co-claro', name: 'Claro', countryId: 'co', logo: ClaroLogo },
    { id: 'co-movistar', name: 'Movistar', countryId: 'co', logo: MovistarLogo },
    { id: 'co-tigo', name: 'Tigo', countryId: 'co', logo: TigoLogo },
    // France
    { id: 'fr-orange', name: 'Orange', countryId: 'fr', logo: OrangeLogo },
    { id: 'fr-sfr', name: 'SFR', countryId: 'fr', logo: SfrLogo },
    { id: 'fr-bouygues', name: 'Bouygues Telecom', countryId: 'fr' },
    // Germany
    { id: 'de-telekom', name: 'Deutsche Telekom', countryId: 'de', logo: DeutscheTelekomLogo },
    { id: 'de-vodafone', name: 'Vodafone', countryId: 'de', logo: VodafoneLogo },
    { id: 'de-o2', name: 'O2', countryId: 'de', logo: O2Logo },
    // Italy
    { id: 'it-tim', name: 'TIM', countryId: 'it', logo: TimLogo },
    { id: 'it-vodafone', name: 'Vodafone', countryId: 'it', logo: VodafoneLogo },
    // Japan
    { id: 'jp-docomo', name: 'NTT Docomo', countryId: 'jp', logo: NttDocomoLogo },
    { id: 'jp-softbank', name: 'SoftBank', countryId: 'jp', logo: SoftbankLogo },
    // Mexico
    { id: 'mx-telcel', name: 'Telcel', countryId: 'mx', logo: TelcelLogo },
    { id: 'mx-att', name: 'AT&T Mexico', countryId: 'mx', logo: AttLogo },
    { id: 'mx-movistar', name: 'Movistar', countryId: 'mx', logo: MovistarLogo },
    // Perú
    { id: 'pe-claro', name: 'Claro', countryId: 'pe', logo: ClaroLogo },
    { id: 'pe-movistar', name: 'Movistar', countryId: 'pe', logo: MovistarLogo },
    { id: 'pe-entel', name: 'Entel', countryId: 'pe', logo: EntelLogo },
    // South Korea
    { id: 'kr-skt', name: 'SK Telecom', countryId: 'kr' },
    { id: 'kr-kt', name: 'KT', countryId: 'kr', logo: KtLogo },
    { id: 'kr-lgup', name: 'LG U+', countryId: 'kr' },
    // Spain
    { id: 'es-movistar', name: 'Movistar', countryId: 'es', logo: MovistarLogo },
    { id: 'es-orange', name: 'Orange', countryId: 'es', logo: OrangeLogo },
    { id: 'es-vodafone', name: 'Vodafone', countryId: 'es', logo: VodafoneLogo },
    // UK
    { id: 'gb-ee', name: 'EE', countryId: 'gb', logo: EeLogo },
    { id: 'gb-o2', name: 'O2', countryId: 'gb', logo: O2Logo },
    { id: 'gb-vodafone', name: 'Vodafone', countryId: 'gb', logo: VodafoneLogo },
    // United States
    { id: 'us-att', name: 'AT&T', countryId: 'us', logo: AttLogo },
    { id: 'us-tmobile', name: 'T-Mobile', countryId: 'us', logo: TMobileLogo },
    { id: 'us-verizon', name: 'Verizon', countryId: 'us', logo: VerizonLogo },
];
