
// This file is auto-generated by `for-each-dev-dependency.js`.
// Do not edit it directly.

export const devDependencies: Record<string, string> = {
  '@types/node': '^20',
  '@types/react': '^18',
  '@types/react-dom': '^18',
  '@types/uuid': '^9.0.8',
  'genkit-cli': '^1.14.1',
  postcss: '^8',
  tailwindcss: '^3.4.1',
  typescript: '^5',
};
